---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Notebook about analysis of bird census data (Book SN) 

- Click on this [link](prepare-data.html) to see how the data were cleaning 

- A first [data exploration analysis](explore-trends.html) was done for the abundance by species. We plotted the abundance of all species by habitat, and then only those species with more than three years along the time period analysed (see `plot_all_HABITAT.pdf` or `plot_selected_HABITAT.pdf` files in `/output/abundance_time`). 

- [**Diversity analysis**](diversity.html) (alpha-divesity) could be found. Graphic outputs are stored at  `/output/diversity`). 

- [**Beta-diversity**](temporal-beta-diversity.html) analysis. Graphic outputs are stored at  `/output/betadiversity`). 

- [**Trend analysis (Mann-Kendall analysis)**](trend-analysis.html) could be found. Graphic outputs are stored at  `/output/mktrend`). 

- Explore [**abundance**](abundance.html). 
- [**Turnover analysis**](turnover.html). 

- A [**report**](report.html) with main of the results obtained. 

- Analysis of [*Garrulus glandarius* and *Turdus torquatus*](arrendajo_mirlo.html)
