---
title: "turnover"
author: "Antonio J Perez-Luque"
date: "2021-05-07"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Turnover Analysis


```{r, set-global-options}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```


```{r load-pkgs}
library("tidyverse")
library("here")
library("codyn")
library("DT")
```

```{r}
passerine <- read_csv(here::here("data/passerine.csv")) 
passerine_abbreviations <- read_csv(here::here("data/passerine_abbrev.csv")) 

passerine.ab <- passerine %>% 
  rename(sp = sp.abb) %>% 
  dplyr::select(-especie) %>% 
  group_by(sp, year, habitat) %>% 
  summarise(ab_avg = round(mean(den, na.rm=TRUE),2), 
            sd = sd(den, na.rm = TRUE), 
            se = sd/sqrt(length(den)), 
            n = length(den))

```

- Generate turnover by year 
```{r}
compute_turnovers <- function(x, var_year, var_sp, var_ab, var_hab,...){
  require(codyn)
  x_turn <- x %>% turnover(time.var = var_year, species.var = var_sp, 
           abundance.var = var_ab, replicate.var = var_hab) %>% 
    rename(value = total) %>% mutate(turnover_metric = "total")
  x_app <- x %>% turnover(time.var = var_year, species.var = var_sp, 
           abundance.var = var_ab, replicate.var = var_hab, 
           metric = "appearance") %>% 
    rename(value = appearance) %>% mutate(turnover_metric = "appearance")
  x_dis <- x %>% turnover(time.var = var_year, species.var = var_sp, 
           abundance.var = var_ab, replicate.var = var_hab, 
           metric = "disappearance") %>% 
    rename(value = disappearance) %>% mutate(turnover_metric = "disappearance")
  
  out <- bind_rows(x_turn, x_app, x_dis)
  return(out)
  
}
```


```{r}
passerie_turnover_all <- compute_turnovers(passerine.ab, var_year = "year", var_sp = "sp", var_ab ="ab_avg", var_hab = "habitat")

write_csv(passerie_turnover_all, file = here::here("output/turnover/passerine_turnover.csv"))

datatable(passerie_turnover_all)
```

- Plot 

```{r}
passerie_turnover_all %>% 
  filter(year != 1985) %>% 
  filter(turnover_metric == "total") %>% 
  ggplot(aes(x=year, y=value, colour = habitat)) + 
  geom_line(size = 1) + 
  theme_bw() + 
  theme(legend.position="bottom") + 
  scale_x_continuous(breaks = seq(2008,2018, by=2), limits=c(2008, 2018))
```


### Compute only for three temporal times 
- Generate three temporal times: 1983; 2009: mean for 2008 - 2009; and 2018: mean for 2017 - 2018. And compute the temporal turnover 

```{r}
df3 <- passerine.ab %>% 
  filter(year %in% c(1981:1985, 2008:2009, 2017:2018)) %>% 
  mutate(yearF = case_when(
    year %in% c(1981:1985) ~ 1983, 
    year %in% c(2008:2009) ~ 2009,
    year %in% c(2017:2018) ~ 2018
  )) %>% 
  group_by(yearF, habitat, sp) %>% 
  summarise(mean = mean(ab_avg, na.rm=TRUE))



df_t1.t2 <- df3 %>% filter(yearF != 2018)
df_t1.t3 <- df3 %>% filter(yearF != 2009)
df_t2.t3 <- df3 %>% filter(yearF != 1983)


turn_t1t2 <- compute_turnovers(df_t1.t2, var_year = "yearF", var_sp = "sp", var_ab ="mean", var_hab = "habitat") %>% mutate(pair = "1980's-2009")

turn_t1t3 <- compute_turnovers(df_t1.t3, var_year = "yearF", var_sp = "sp", var_ab ="mean", var_hab = "habitat") %>% mutate(pair = "1980's-2018")

turn_t2t3 <- compute_turnovers(df_t2.t3, var_year = "yearF", var_sp = "sp", var_ab ="mean", var_hab = "habitat") %>% mutate(pair = "2009-2018")

passerie_turnover_compare <- bind_rows(turn_t1t2, turn_t1t3, turn_t2t3)


write_csv(passerie_turnover_compare, file = here::here("output/turnover/passerine_turnover_compare.csv"))
```


```{r}
colturnover <- c("total"="#B3B3B3", "appearance" = "#8DA0CB", 
                "disappearance"= "#E5C494")

passerie_turnover_compare %>% 
  ggplot(aes(x=pair, y=value, 
             fill=turnover_metric)) + 
  geom_bar(stat="identity", position = "dodge2") + 
  facet_wrap(~habitat, nrow=3) + 
  theme_bw() + 
  theme(legend.position="bottom", 
        legend.title = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank()
  ) +
    scale_fill_manual(values = colturnover) +
  xlab("") + ylab("Turnovers (%)")

```











